config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
get 'question', to: 'pages#question'
get 'answer', to: 'pages#answer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def question
  end

  def answer


end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/answer.html.erb
<H1> Stupid Coaching </H1>


<div class = "question">
  <%= params[:question] %>
  <p> -You </p>
</div>

<div class = "question coach">
<% if params[:question]=="I am going to work" %>
        <h2> Great </h2>
     <% elsif params[:question].include? "?" %>
       <h2> Silly question, get dressed and go to work! </h2>
    <% else %>
     <h2> I don't care </h2>
<% end %>
<p>-Coach </p>
</div>



<%= link_to'Ask a new question', question_path %>

app/views/pages/question.html.erb
<H1> Stupid Coaching </H1>

<div class = "ask-form">
<form action="/answer">
  <label for="question">Speak to your coach</label>
  <input type="text" id="question" name="question" placeholder="what time is it?">
  <input type="submit" value="Go on!">
</form>
</div>